{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from random import choice, randint, sample, randrange\n",
    "from string import punctuation\n",
    "\n",
    "from Adversary.constants import *\n",
    "\n",
    "'''These act on a single text'''\n",
    "\n",
    "\n",
    "def good_word_attack(text):\n",
    "    if randint(1, 2) == 1:\n",
    "        return text + ' ' + ' '.join(sample(NEUTRAL_WORDS, randint(5, 15)))\n",
    "    else:\n",
    "        return ' '.join(sample(NEUTRAL_WORDS, randint(2, 10))) + ' ' + text\n",
    "\n",
    "\n",
    "def swap_words(text):\n",
    "    words = text.split()\n",
    "    if len(words) <= 3:\n",
    "        return ' '.join(words)\n",
    "    swapped = list(range(len(words)))\n",
    "    idxs = sample(range(1, len(words) - 2), randint(1, min(3, len(words) // 2 - 1)))\n",
    "    for i in idxs:\n",
    "        swapped[i], swapped[i + 1] = swapped[i + 1], swapped[i]\n",
    "    return ' '.join([words[i] for i in swapped])\n",
    "\n",
    "\n",
    "def remove_spacing(text):\n",
    "    chars = list(text)\n",
    "    for i, c in enumerate(chars):\n",
    "        if c == ' ' and randint(1, 3) == 1:\n",
    "            chars[i] = choice(',.-'\"`*\")\n",
    "    return ''.join(chars)\n",
    "\n",
    "\n",
    "'''These act on a single word within a text'''\n",
    "\n",
    "\n",
    "def synonym(word):\n",
    "    return choice(SYNONYMS.get(word, [word]))\n",
    "\n",
    "\n",
    "def letter_to_symbol(word):\n",
    "    return ''.join([choice(HOMOGLPYH_MAP.get(c.lower(), [c])) for c in word])\n",
    "\n",
    "\n",
    "def swap_letters(word):\n",
    "    if len(word) < 4:\n",
    "        return word\n",
    "    swapped = list(range(len(word)))\n",
    "    max_swap = randint(1, min(3, len(word) // 2 - 1))\n",
    "    idxs = sample(range(1, len(word) - 2), max_swap)\n",
    "    for i in idxs:\n",
    "        swapped[i], swapped[i + 1] = swapped[i + 1], swapped[i]\n",
    "    return ''.join([word[i] for i in swapped])\n",
    "\n",
    "\n",
    "def insert_punctuation(word):\n",
    "    word_with_punct = list(word)\n",
    "    for _ in range(2):\n",
    "        word_with_punct.insert(randrange(len(word_with_punct)), choice(punctuation))\n",
    "    return ''.join(word_with_punct)\n",
    "\n",
    "\n",
    "def insert_duplicate_characters(word):\n",
    "    word_with_dupes = list(word)\n",
    "    for _ in range(2):\n",
    "        i = randrange(len(word_with_dupes))\n",
    "        word_with_dupes.insert(i, word_with_dupes[i])\n",
    "    return ''.join(word_with_dupes)\n",
    "\n",
    "\n",
    "def delete_characters(word):\n",
    "    if len(word) < 4:\n",
    "        return word\n",
    "    max_del = 1 if len(word) <= 5 else 2\n",
    "    idxs_delete = sample(range(1, len(word) - 1), max_del)\n",
    "    return ''.join([c for i, c in enumerate(\n",
    "        list(word)) if i not in idxs_delete])\n",
    "\n",
    "\n",
    "def change_case(word):\n",
    "    word_with_changed_case = list(word)\n",
    "    idx = sample(range(len(word)), randint(1, len(word)))\n",
    "    for i in idx:\n",
    "        c = word[i]\n",
    "        word_with_changed_case[i] = c.upper() if c.lower() == c else c.lower()\n",
    "    return ''.join(word_with_changed_case)\n",
    "\n",
    "\n",
    "def num_to_word(word):\n",
    "    return NUM_TO_WORD.get(word, word)\n",
    "\n",
    "\n",
    "'''Keeps track of all attacks and their types'''\n",
    "\n",
    "\n",
    "ATTACK_MAP = {\n",
    "    'text': {\n",
    "        'good_word_attack': good_word_attack,\n",
    "        'swap_words': swap_words,\n",
    "        'remove_spacing': remove_spacing,\n",
    "    },\n",
    "    'word': {\n",
    "        'synonym': synonym,\n",
    "        'letter_to_symbol': letter_to_symbol,\n",
    "        'swap_letters': swap_letters,\n",
    "        'insert_punctuation': insert_punctuation,\n",
    "        'insert_duplicate_characters': insert_duplicate_characters,\n",
    "        'delete_characters': delete_characters,\n",
    "        'change_case': change_case,\n",
    "        'num_to_word': num_to_word\n",
    "    }\n",
    "}\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
